/*
Copyright The CloudNativePG Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePoolers implements PoolerInterface
type FakePoolers struct {
	Fake *FakePostgresqlV1
	ns   string
}

var poolersResource = v1.SchemeGroupVersion.WithResource("poolers")

var poolersKind = v1.SchemeGroupVersion.WithKind("Pooler")

// Get takes name of the pooler, and returns the corresponding pooler object, and an error if there is any.
func (c *FakePoolers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Pooler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(poolersResource, c.ns, name), &v1.Pooler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Pooler), err
}

// List takes label and field selectors, and returns the list of Poolers that match those selectors.
func (c *FakePoolers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PoolerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(poolersResource, poolersKind, c.ns, opts), &v1.PoolerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.PoolerList{ListMeta: obj.(*v1.PoolerList).ListMeta}
	for _, item := range obj.(*v1.PoolerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested poolers.
func (c *FakePoolers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(poolersResource, c.ns, opts))

}

// Create takes the representation of a pooler and creates it.  Returns the server's representation of the pooler, and an error, if there is any.
func (c *FakePoolers) Create(ctx context.Context, pooler *v1.Pooler, opts metav1.CreateOptions) (result *v1.Pooler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(poolersResource, c.ns, pooler), &v1.Pooler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Pooler), err
}

// Update takes the representation of a pooler and updates it. Returns the server's representation of the pooler, and an error, if there is any.
func (c *FakePoolers) Update(ctx context.Context, pooler *v1.Pooler, opts metav1.UpdateOptions) (result *v1.Pooler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(poolersResource, c.ns, pooler), &v1.Pooler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Pooler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePoolers) UpdateStatus(ctx context.Context, pooler *v1.Pooler, opts metav1.UpdateOptions) (*v1.Pooler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(poolersResource, "status", c.ns, pooler), &v1.Pooler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Pooler), err
}

// Delete takes name of the pooler and deletes it. Returns an error if one occurs.
func (c *FakePoolers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(poolersResource, c.ns, name, opts), &v1.Pooler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePoolers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(poolersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.PoolerList{})
	return err
}

// Patch applies the patch and returns the patched pooler.
func (c *FakePoolers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Pooler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(poolersResource, c.ns, name, pt, data, subresources...), &v1.Pooler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Pooler), err
}
